### ISSUE TITLE
Channel based rejection as rejection threshold in MNE + averaged reference 

### ISSUE THREAD

**Issue by AmirDJV** [autoreject/autoreject#125]
I apologize for being a noob but I have two questions: 

1. While [`get_rejection_threshold`](http://autoreject.github.io/generated/autoreject.get_rejection_threshold.html#autoreject.get_rejection_threshold) returns a global rejection thresholds as a dictionary of number per key (‘mag’, ‘grad’, ‘eeg’, ‘eog’ and ‘ecg’),[`compute_thresholds`](http://autoreject.github.io/generated/autoreject.compute_thresholds.html#autoreject.compute_thresholds) returns a dictionary of number per channel. All makes sense to me.
However, how can I implement it in MNE? All function accept the argument `reject=` which doesn't work with the output of `compute_thresholds`. 
2. Given that I rejected a channel in only some of my epochs, how does average referencing deal with it? 

Thank you!

**Comment by jasmainak** [comment]
Hi @AmirDJV you shouldn't be using `compute_thresholds`. It's mostly for demo purposes in the example. For using the channel-specific thresholds, you should use the [`AutoReject`](http://autoreject.github.io/generated/autoreject.AutoReject.html#autoreject.AutoReject) class which internally calls `compute_thresholds`. See [here](http://autoreject.github.io/auto_examples/plot_visualize_bad_epochs.html#sphx-glr-auto-examples-plot-visualize-bad-epochs-py) for a demo.

> Given that I rejected a channel in only some of my epochs, how does average referencing deal with it?

what you describe is not different from a regular rejection. It also involves rejecting a channel for some epochs. It's true that sometimes certain channels in an epoch would be interpolated, but this would only give you a better estimate of average reference -- rather than having the artifactual data in there.

**Comment by AmirDJV** [comment]
Hi @jasmainak  thank you very much for your response!

Based on the [FAQ](http://autoreject.github.io/faq.html) I thought it would be possible to run something close to the below but with `compute_thresholds`. Thank you very much for the clarification. I'll use it as you said :) 

```
reject = get_rejection_threshold(epochs)
ica.fit(epochs, reject=reject)
```
I'm dealing with continuance data so "normal" epoching doesn't necessarily makes sense in my case. Thus, I was looking for something I could use with the argument `reject=reject`. However, I could probably just epoch my data and use "manual" annotation using the extracted times of the bad epochs. 



Regarding my question: 

> Given that I rejected a channel in only some of my epochs, how does average referencing deal with it?

I didn't took into account the idea of interpolating data, only removing. Therefore, I was wondering how would average referencing would work in the example below. While the second and third epochs will be removed, in the first epoch only the T8, P7, and P8 are problematic. Would the average reference include or exclude them from the calculation? or would it exclude the epoch? 


![annotation 2019-02-04 103626](https://user-images.githubusercontent.com/25877896/52197715-24778300-2869-11e9-97df-c5b94aa4ee68.jpg)

**Comment by jasmainak** [comment]
> However, I could probably just epoch my data and use "manual" annotation using the extracted times of the bad epochs.

Yes, look into the MNE `Annotations` object. The `ica.fit` in MNE is probably aware of it -- so if you set annotations in raw using autoreject, you might be able to do what you want. But you'll have to create the annotations yourself.

> Therefore, I was wondering how would average referencing would work in the example below. While the second and third epochs will be removed, in the first epoch only the T8, P7, and P8 are problematic. Would the average reference include or exclude them from the calculation? or would it exclude the epoch?

In the first epoch, note that T8 will not be interpolated or rejected. It was marked as bad by the channel-wise threshold but no action will be taken upon it by autoreject since it's not too bad. However, P7 and P8 will be interpolated.

Now, MNE is not automatically aware of autoreject. The only thing MNE knows is what is inside the `epochs` object -- the `epochs.info['bads']` (which is not set by autoreject) and `epochs.reject_log` (which contains the list of bad channels). In case you manually use [`set_eeg_reference`][https://martinos.org/mne/stable/generated/mne.set_eeg_reference.html] it will take into account `epochs.info['bads']`. But otherwise, it does not know what is an interpolated channel and what is not. So it will take the average of all the channels for all the good epochs when computing the average reference.

**Comment by AmirDJV** [comment]
Thank you for your help and for the amazing thing you (all) doing here ! :)
