### ISSUE TITLE
optimizer/optimizer.py:195: UserWarning: The objective has been evaluated at this point before.

### ISSUE THREAD

**Issue by janfreyberg** [autoreject/autoreject#32]
I'm getting the same warning message over and over again when trying to use `LocalAutoRejectCV` using all defaults. My code is roughly:

```python
import mne
from autoreject import LocalAutoRejectCV

raws = [mne.io.read_raw_edf(file, eog=['EXG' + str(i) for i in range(9)],
                            montage=mne.channels.read_montage('biosemi64'),
                            verbose='WARNING')
       for file in files]

picks = [mne.pick_types(raw.info, eeg=True) for raw in raws]

events = [mne.find_events(raw, stim_channel='STI 014', verbose='WARNING')
          for raw in raws]

eventids = [event[:, 2][event[:, 2] < 255].tolist()
            for event in events]

epochs = [mne.Epochs(raw, events=event, event_id=eventid,
                     tmin=0, tmax=16, add_eeg_ref=False,
                     picks=pick,
                     verbose='WARNING')
          for raw, event, eventid, pick in zip(raws, events, eventids, picks)]

epoch = epochs[0]
epoch.load_data()
epoch.resample(256)

reject = LocalAutoRejectCV(epoch)
clean_epochs = reject.fit_transform(epoch)

```

This warning comes up seemingly on every iteration of the fit_transform call (more than 100 warnings):
```
/Library/anaconda/envs/py36/lib/python3.6/site-packages/skopt/optimizer/optimizer.py:195:
UserWarning: The objective has been evaluated at this point before.
```

Am I doing something wrong here?

**Comment by janfreyberg** [comment]
PS:
```
autoreject==0.1.dev0
scikit-optimize==0.3
mne==0.14.dev0
```

**Comment by jasmainak** [comment]
Hi @janfreyberg thanks for reporting this. Indeed, I observed this with `scikit-optimize==0.3` as well. It looks harmless to me but I'm not sure why it's showing so many of them. If you don't want to see the warning, you can probably downgrade to `scikit-optimize==0.1` (or maybe 0.2, not sure ...). 

FWIW, we are planning to remove the dependency on `scikit-optimize` so that we can better control what's going on with the Bayesian optimization. See https://github.com/autoreject/autoreject/pull/31, it should be merged soon!

**Comment by janfreyberg** [comment]
Cool, thanks!

I'll downgrade for now, but look forward to trying the new code :)

**Comment by jasmainak** [comment]
okay closing this now as https://github.com/autoreject/autoreject/pull/31 has been merged. Feel free to try it and let us know :)

**Comment by janfreyberg** [comment]
Will do, thanks!
